<?php

namespace Database\Seeders;

use App\Models\Vecino;
use Illuminate\Database\Seeder;

class VecinoSeeder extends Seeder
{
    public function run(): void
    {
        $vecinos = [
            ['nombres_apellidos' => 'Andres Yañez Campos', 'comuna_residencia' => 'Puerto Montt', 'telefono' => '956468506', 'correo' => 'andresyanezcampos@gmail.com', 'etapa' => 'II', 'numero_parcela' => '5', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Facebook', 'contacto_vendedor_nombre' => 'karla martinez', 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => null, 'valor_terreno' => 7840000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => 'pie + cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Diego Espinosa Salinas', 'comuna_residencia' => 'Santiago', 'telefono' => '982737915', 'correo' => 'despinosas.de@gmail.com', 'etapa' => 'I', 'numero_parcela' => '8', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Facebook', 'contacto_vendedor_nombre' => 'Gloria Artigas', 'medio_contacto_vendedor' => 'Whatsapp, Email', 'fecha_firma_contrato' => '2021-04-27', 'valor_terreno' => 9801000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Inversiones Latam Spa\n77.141.857-0\nCuenta Corriente 00-004-61868-83\nBci Mach\ntupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => '1 millon en pie y al contado 8.800.000. Entrega virtual 2023. Pactado para el 2022', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Claudia Flores Quintero', 'comuna_residencia' => null, 'telefono' => '945363399', 'correo' => 'claudiafloresquintero@gmail.com', 'etapa' => 'II', 'numero_parcela' => '8', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Camilo Cardenas', 'comuna_residencia' => null, 'telefono' => '935857569', 'correo' => 'Camilo.cardenas@hotmail.com', 'etapa' => 'II', 'numero_parcela' => '13', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Rodrigo Rojas Velasquez', 'comuna_residencia' => 'Viña del Mar', 'telefono' => '974427504', 'correo' => 'rodrigorojasv@gmail.com', 'etapa' => 'I', 'numero_parcela' => '14', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram y web', 'contacto_vendedor_nombre' => 'Moises Arroyo', 'medio_contacto_vendedor' => 'Whatsapp, Teléfono, Email', 'fecha_firma_contrato' => '2021-03-03', 'valor_terreno' => 8690000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => 'Pie + cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Patricio Cabrera', 'comuna_residencia' => 'Buin', 'telefono' => '933186664', 'correo' => 'patricio.cabrera.ar@gmail.com', 'etapa' => 'II', 'numero_parcela' => '19', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Tracy Dunstan', 'medio_contacto_vendedor' => 'Whatsapp, Teléfono, Email', 'fecha_firma_contrato' => '2021-04-14', 'valor_terreno' => 13890000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: inversiones latam spa\nBanco: BCI\nCuenta Corriente: 0-000-46-18688-3\nRUT: 77.141.857-0\nMail: tupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => 'Pie + 20 cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Manuel Gonzalez Nahuelan', 'comuna_residencia' => null, 'telefono' => '944041548', 'correo' => 'me.gonzalezn@hotmail.com', 'etapa' => 'II', 'numero_parcela' => '21', 'como_se_entero' => 'Otro', 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'Moises Arroyo', 'medio_contacto_vendedor' => 'Whatsapp / Email', 'fecha_firma_contrato' => null, 'valor_terreno' => 14000000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: inversiones latam spa\nBanco: BCI\nCuenta Corriente: 0-000-46-18688-3\nRUT: 77.141.857-0\nMail: tupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Gabriela León García', 'comuna_residencia' => 'Padre Hurtado', 'telefono' => '984626037', 'correo' => 'gaby_leon7@hotmail.com', 'etapa' => 'II', 'numero_parcela' => '22', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Nancy subiabre', 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => '2022-09-05', 'valor_terreno' => 12501000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Inversiones Latam Spa\nRut 77.141.857-0\nCuenta 75715650\nBanco Santander\ntupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => 'Contado entrega marzo 2023', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Merjai Constanza Vergara', 'comuna_residencia' => null, 'telefono' => '930352664', 'correo' => 'merjaivergara99@gmail.com', 'etapa' => 'II', 'numero_parcela' => '23', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Nataly Leal Gutiérrez', 'comuna_residencia' => null, 'telefono' => '957691692', 'correo' => 'Nataly_leal24@hotmail.com', 'etapa' => 'I', 'numero_parcela' => '23', 'como_se_entero' => 'rrss', 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Andrea Karina Negrete Quezada / Maria Teresa Quezada', 'comuna_residencia' => 'Quilicura', 'telefono' => '975261084 / 949478979', 'correo' => 'andreakarinanq@gmail.com / marritequezada@gmail.com', 'etapa' => 'II', 'numero_parcela' => '24', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Solange Vallejos', 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => '2021-04-13', 'valor_terreno' => 9320000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Inversiones Latam Spa\n77.141.857-0\nCuenta Corriente 00-004-61868-83\nBci Mach\ntupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => "1 millón de pie y 20 cuotas.\nEntrega en marzo 2023", 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => "Natalia sepulveda villalobos\nGerman reinoso alvarado", 'comuna_residencia' => 'Santiago', 'telefono' => '945075708', 'correo' => "Nsepulvedavillalobos@gmail.com\nGermanreinosoa@gmail.com", 'etapa' => 'I', 'numero_parcela' => '24', 'como_se_entero' => 'RRSS', 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'Magaly vargas', 'medio_contacto_vendedor' => 'Email', 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Ayleen Hernandez', 'comuna_residencia' => null, 'telefono' => '958681335', 'correo' => 'ru.ayleen@gmail.com', 'etapa' => 'I', 'numero_parcela' => '25', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Jorge Contreras', 'comuna_residencia' => 'Temuco', 'telefono' => '965380633', 'correo' => 'contrerastaz.jsca@gmail.com', 'etapa' => 'I', 'numero_parcela' => '27', 'como_se_entero' => 'Redes', 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => '2025-06-23', 'valor_terreno' => 9000000, 'forma_pago' => 'Trasferencia', 'datos_cuenta_pago' => "Nombre: Inversiones Latam Spa\nRUT: 77.141.857-0\nTipo de cuenta BCI: Cuenta Corriente\nN° de Cuenta: 46186883", 'plazo_pago_entrega' => 'Pie y letras al contado', 'registro_pagos' => 'Si', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Oscar Daniel Espinoza Vergara', 'comuna_residencia' => null, 'telefono' => '996940531', 'correo' => 'osc.esp.ver@gmail.com', 'etapa' => 'II', 'numero_parcela' => '28', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Giorgio Caffi', 'comuna_residencia' => 'Olmue', 'telefono' => '985291107', 'correo' => 'giorgio_caffi@hotmail.com', 'etapa' => 'II', 'numero_parcela' => '31', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Ema Lantaño Muñoz', 'comuna_residencia' => 'Santiago', 'telefono' => '950120221', 'correo' => 'ema.lantano.m@gmail.com', 'etapa' => 'II', 'numero_parcela' => '32', 'como_se_entero' => 'Dato de Terceros', 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'Magaly vargas', 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => '2021-01-25', 'valor_terreno' => 12890000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: Inversiones Latam Spa\nRUT: 77.141.857-0\nTipo de cuenta Santander: Cuenta Corriente\nN° de Cuenta: 75715650", 'plazo_pago_entrega' => 'Pie + cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Marcos Caceres', 'comuna_residencia' => null, 'telefono' => '89009246', 'correo' => 'marcoscaceresrojas@yahoo.com', 'etapa' => 'I', 'numero_parcela' => '32', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Malvina Requena corredora de propiedades Marcia Propiedades', 'medio_contacto_vendedor' => 'Email', 'fecha_firma_contrato' => '2023-07-31', 'valor_terreno' => 15392944, 'forma_pago' => 'Cheque', 'datos_cuenta_pago' => 'Vale vista', 'plazo_pago_entrega' => 'contado', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Carlos Céspedes López', 'comuna_residencia' => 'Maipú', 'telefono' => '956272589', 'correo' => 'c.cespedes.lopez@gmail.com', 'etapa' => 'II', 'numero_parcela' => '34', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Daniela Osben', 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => '2021-03-09', 'valor_terreno' => 13890000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => '46186883', 'plazo_pago_entrega' => 'Pie de 2.000.000 + 31 cuotas de 383.548', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Javiera Alejandra Peters Cummins', 'comuna_residencia' => 'Arica', 'telefono' => '984137809', 'correo' => 'javiera.peters@inacapmail.cl', 'etapa' => 'I', 'numero_parcela' => '34', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Facebook', 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => 'Email', 'fecha_firma_contrato' => '2023-07-11', 'valor_terreno' => 9320000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: Inversiones Latam Spa\nRUT: 77.141.857-0\nTipo de cuenta BCI: Cuenta Corriente\nN° de Cuenta: 46186883", 'plazo_pago_entrega' => 'pie + cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Pablo Andrades', 'comuna_residencia' => null, 'telefono' => '962183976', 'correo' => '-', 'etapa' => 'II', 'numero_parcela' => '38', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Ruth Sanhueza', 'comuna_residencia' => 'Concepción', 'telefono' => '934334583', 'correo' => 'ruthysanhuezav@gmail.com', 'etapa' => 'I', 'numero_parcela' => '39', 'como_se_entero' => 'Dato de Terceros', 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'Ximena Artigas', 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => '2021-02-27', 'valor_terreno' => 7840000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: inversiones latam spa\nBanco: BCI\nCuenta Corriente: 0-000-46-18688-3\nRUT: 77.141.857-0\nMail: tupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => null, 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Moises Enrique Zuñiga Chiguay', 'comuna_residencia' => 'Santiago', 'telefono' => '961246813', 'correo' => 'moises.zuniga.ch@gmail.com', 'etapa' => 'II', 'numero_parcela' => '42', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Faceboock', 'contacto_vendedor_nombre' => 'Amarys Martinez', 'medio_contacto_vendedor' => 'Email', 'fecha_firma_contrato' => '2021-04-01', 'valor_terreno' => 9338000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: Inversiones Latam Spa\nRUT: 77.141.857-0\nTipo de cuenta Santander: Cuenta Corriente\nN° de Cuenta: 75715650", 'plazo_pago_entrega' => 'Pie + cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Rashel Sáez / Mauricio Novoa', 'comuna_residencia' => null, 'telefono' => '993299815 / 994770991', 'correo' => 'rashel.saez@gmail.com', 'etapa' => 'II', 'numero_parcela' => '47', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Carlos Lara', 'comuna_residencia' => 'Concepción', 'telefono' => '920182313', 'correo' => 'carlos.lara@ucsc.cl', 'etapa' => 'I', 'numero_parcela' => '48', 'como_se_entero' => 'RRSS', 'medio_difusion' => 'instagram', 'contacto_vendedor_nombre' => 'Moises Arroyo', 'medio_contacto_vendedor' => 'Whatsapp / Email', 'fecha_firma_contrato' => null, 'valor_terreno' => 6952000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: inversiones latam spa\nBanco: BCI\nCuenta Corriente: 0-000-46-18688-3\nRUT: 77.141.857-0\nMail: tupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => 'pagada', 'registro_pagos' => 'si', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Rey David Villegas Lopez / Karen Sangrona', 'comuna_residencia' => 'Valdivia', 'telefono' => '998279291', 'correo' => 'gfsrey@gmail.com', 'etapa' => 'I', 'numero_parcela' => '50', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Katherine Rodríguez', 'comuna_residencia' => 'Hualañé', 'telefono' => '990522170', 'correo' => 'k.rodriguez.acuna@gmail.com', 'etapa' => 'II', 'numero_parcela' => '51', 'como_se_entero' => 'Dato de Terceros', 'medio_difusion' => 'No aplica', 'contacto_vendedor_nombre' => 'Solange Vallejos (Asesora inmobiliaria, ya no trabaja ahí)', 'medio_contacto_vendedor' => 'Teléfono, Whatsapp, Email', 'fecha_firma_contrato' => '2023-05-26', 'valor_terreno' => 9338000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: inversiones latam spa\nBanco: BCI\nCuenta Corriente: 0-000-46-18688-3\nRUT: 77.141.857-0\nMail: tupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => "1 millón de pie y 20 cuotas.\nEntrega en marzo 2023", 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Carolina Viera Salazar', 'comuna_residencia' => 'La Florida', 'telefono' => '976673576', 'correo' => 'carolina.v.s@gmail.com', 'etapa' => 'I', 'numero_parcela' => '56', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Facebook/instagram', 'contacto_vendedor_nombre' => 'Daniella Osben (asesora de ventas, ya no trabaja ahí)', 'medio_contacto_vendedor' => 'Whatsapp, Teléfono, Email', 'fecha_firma_contrato' => '2021-12-20', 'valor_terreno' => 7821000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: inversiones latam spa\nBanco: BCI\nCuenta Corriente: 0-000-46-18688-3\nRUT: 77.141.857-0\nMail: tupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => 'Pago al contado', 'registro_pagos' => null, 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Luz Quezada', 'comuna_residencia' => 'Peñaflor', 'telefono' => '961704926', 'correo' => 'lkquezada@gmail.com', 'etapa' => 'I', 'numero_parcela' => '56', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'Camila Alarcón', 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => 'Pago en cuotas', 'registro_pagos' => 'Si', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Emilio Carreño', 'comuna_residencia' => 'Puente Alto', 'telefono' => '963402217', 'correo' => 'ecarreno8@gmail.com', 'etapa' => 'II', 'numero_parcela' => '57', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Johnny Ceballos', 'medio_contacto_vendedor' => 'Whatsapp, Teléfono, Email', 'fecha_firma_contrato' => '2021-04-07', 'valor_terreno' => 9320000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: Inversiones Latam Spa\nRUT: 77.141.857-0\nTipo de cuenta Santander: Cuenta Corriente\nN° de Cuenta: 75715650", 'plazo_pago_entrega' => 'Pie + 20 cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Héctor Eladio Inzunza Vargas', 'comuna_residencia' => 'Puente Alto', 'telefono' => '993558699', 'correo' => 'hector.lapidador@gmail.com', 'etapa' => 'I', 'numero_parcela' => '57', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Ximena artigas', 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => '2021-04-13', 'valor_terreno' => 9094800, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: inversiones latam spa\nBanco: BCI\nCuenta Corriente: 0-000-46-18688-3\nRUT: 77.141.857-0\nMail: tupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => 'pie+ cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Completamente pagada, pero no inscrita'],
            ['nombres_apellidos' => 'Juan Ignacio San Martín', 'comuna_residencia' => 'Peñalolén', 'telefono' => '984703830', 'correo' => 'j.sanmartínlanderos@gmail.com', 'etapa' => 'I', 'numero_parcela' => '58', 'como_se_entero' => 'dato de terceros', 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'camila Alarcón', 'medio_contacto_vendedor' => 'WhatsApp/Email', 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => 'si', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Johanna Alarcon Lobos', 'comuna_residencia' => null, 'telefono' => '964436922', 'correo' => '1189lobos@gmail.com /  alarconlobosjohanna@gmail.com', 'etapa' => 'I', 'numero_parcela' => '59', 'como_se_entero' => 'Otro', 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'Moises Arroyo', 'medio_contacto_vendedor' => 'Telefono', 'fecha_firma_contrato' => '2022-11-17', 'valor_terreno' => 11900000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: inversiones latam spa\nBanco: BCI\nCuenta Corriente: 0-000-46-18688-3\nRUT: 77.141.857-0\nMail: tupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => 'Pie + 24cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita en cbr'],
            ['nombres_apellidos' => 'María Cristina Escarate Ramos', 'comuna_residencia' => 'Santiago', 'telefono' => '9 9499 5321', 'correo' => 'mcescarate@gmail.com', 'etapa' => 'II', 'numero_parcela' => '59', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Humberto Arturo Hernandez Vasquez', 'comuna_residencia' => 'Pudahuel', 'telefono' => '56984227251', 'correo' => 'hmbrt.personal@gmail.com', 'etapa' => 'II', 'numero_parcela' => '60', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Daniela Osben', 'medio_contacto_vendedor' => 'Whatsapp, Email', 'fecha_firma_contrato' => '2021-04-09', 'valor_terreno' => 13890000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => 'Pie de 1.000.000 el saldo en 31 coutas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Humberto Figari Moscoso', 'comuna_residencia' => null, 'telefono' => '962243451', 'correo' => 'htofigari1964@gmail.com', 'etapa' => 'I', 'numero_parcela' => '60', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Pablo Angulo', 'comuna_residencia' => 'Antofagasta', 'telefono' => '984713495', 'correo' => 'pablo.bajista@gmail.com', 'etapa' => 'I', 'numero_parcela' => '61', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Carlos Sotelo / Evelyn Fierro', 'comuna_residencia' => 'Villarrica', 'telefono' => '981914912', 'correo' => 'evelyn.fierro.pino@gmail.com', 'etapa' => 'll', 'numero_parcela' => '65', 'como_se_entero' => 'RRSS', 'medio_difusion' => 'Facebook', 'contacto_vendedor_nombre' => 'Eugenio', 'medio_contacto_vendedor' => 'WhatsApp', 'fecha_firma_contrato' => null, 'valor_terreno' => 10000000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => 'pagada contado', 'registro_pagos' => 'si', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Juan Carlos Ibarra vargas', 'comuna_residencia' => 'Melipilla', 'telefono' => '985901014', 'correo' => 'jibarravargas@gmail.com', 'etapa' => 'I', 'numero_parcela' => '66', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Camila Alarcon', 'medio_contacto_vendedor' => 'Email, Whatsapp, Teléfono', 'fecha_firma_contrato' => '2021-08-24', 'valor_terreno' => 13890000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => 'SI', 'estado_parcela' => 'Completamente pagada, pero no inscrita'],
            ['nombres_apellidos' => 'Alejandra Delgado Arancibia / Richard Cavieres', 'comuna_residencia' => 'Viña del mar', 'telefono' => '977535899 / 938993064', 'correo' => 'alejandradelgadoa21@gmail.com // richardedison2009@gmail.com', 'etapa' => 'I', 'numero_parcela' => '68', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Facebook', 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => '2023-11-15', 'valor_terreno' => 7840000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => 'la mitad el resto en 17 cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Tomás Ramdohr / Nicole Muñoz', 'comuna_residencia' => 'Providencia', 'telefono' => '933900823', 'correo' => 'to.ramdohr@gmail.com', 'etapa' => 'I', 'numero_parcela' => '69', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'instagram', 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => 'Email', 'fecha_firma_contrato' => '2021-02-22', 'valor_terreno' => null, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => 'Vale vista', 'plazo_pago_entrega' => 'Contado', 'registro_pagos' => 'si', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Claudia Vega', 'comuna_residencia' => 'Copiapó', 'telefono' => '920649812', 'correo' => 'keyloma@gmail.com', 'etapa' => 'II', 'numero_parcela' => '70', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Leonardo Troncoso', 'comuna_residencia' => 'Santiago', 'telefono' => '972138009', 'correo' => 'leonardo.troncoso.a@gmail.com', 'etapa' => 'I', 'numero_parcela' => '71', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Francisco Díaz', 'comuna_residencia' => null, 'telefono' => '950080780', 'correo' => 'franciscodiazmeneses@gmail.com', 'etapa' => 'II', 'numero_parcela' => '71', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Yanet Hermosilla Cifuentes', 'comuna_residencia' => 'Valdivia', 'telefono' => '9 5093 2450', 'correo' => 'yanethermosillacifuentes@hotmail.com', 'etapa' => 'I', 'numero_parcela' => '72', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Scarlet Orellana Rodriguez', 'comuna_residencia' => 'Puente Alto', 'telefono' => '978940787', 'correo' => 'Scarletorellana.r@gmail.com', 'etapa' => 'I', 'numero_parcela' => '73', 'como_se_entero' => 'Dato de Terceros', 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'Fernando Rees - Javiera Sanhueza - Jocelyn Vergara', 'medio_contacto_vendedor' => 'Email', 'fecha_firma_contrato' => '2024-05-30', 'valor_terreno' => 15890000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: Inversiones Latam Spa\nRUT: 77.141.857-0\nTipo de cuenta Santander: Cuenta Corriente\nN° de Cuenta: 89821894", 'plazo_pago_entrega' => 'Pie + cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Completamente pagada, pero no inscrita'],
            ['nombres_apellidos' => 'Ninón Zalaquett y Felipe Arriaza', 'comuna_residencia' => 'Peñalolén', 'telefono' => '9 5659 4123', 'correo' => 'ninonzalaquett@gmail.com - felipe.arriaza@ug.uchile.cl', 'etapa' => 'II', 'numero_parcela' => '74', 'como_se_entero' => 'Dato de Terceros', 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'Moisés Arroyo', 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => '2021-05-04', 'valor_terreno' => 9320000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => 'Inversiones Latam SPA 77.141.857-0 BANCO DE CREDITO E INVERSIONES Cuenta Corriente Numero 46186883 tupagoaldia@inversioneslatam.cl', 'plazo_pago_entrega' => 'Pie y 24 cuotas. Última cuota Febrero 2023. La fecha de entrega del terreno según contrato de compra venta era en abril 2023', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Brian Christiansen', 'comuna_residencia' => null, 'telefono' => '941264095 / 934059326', 'correo' => 'Brian.christiansen@hotmail.cl', 'etapa' => 'II', 'numero_parcela' => '75', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'María Ignacia Flores Vilches', 'comuna_residencia' => 'Isla de Maipo', 'telefono' => '953768850', 'correo' => 'mariaignacia.floresv@gmail.com', 'etapa' => 'I', 'numero_parcela' => '76', 'como_se_entero' => 'Dato de Terceros', 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'Malvinas Requena', 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'María Alejandra Contreras', 'comuna_residencia' => 'Peñalolen', 'telefono' => '993502197', 'correo' => 'drawaychile@gmail.com', 'etapa' => 'll', 'numero_parcela' => '76', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => 'pagada', 'registro_pagos' => 'si', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Hector Valentin Paredes Fuentealba / Pamela Fredes', 'comuna_residencia' => 'Melipilla', 'telefono' => '974325904', 'correo' => 'pamefredes.h@gmail.com', 'etapa' => 'I', 'numero_parcela' => '77', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'MAGALY Vargas(asesora de la inmoviliaria)', 'medio_contacto_vendedor' => 'Teléfono, Whatsapp, Email', 'fecha_firma_contrato' => '2021-02-19', 'valor_terreno' => 7840000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => 'Pie + cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Ricardo Herrera / Ronald Riveros', 'comuna_residencia' => 'Quilicura', 'telefono' => '944865954 / 952069225', 'correo' => 'hadesquake@gmail.com / ronald.riveros.m@gmail.com', 'etapa' => 'I', 'numero_parcela' => '11 y 22', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Karla Martinez (asesora inmobiliaria, ya no trabaja ahi)', 'medio_contacto_vendedor' => 'Whatsapp', 'fecha_firma_contrato' => '2021-03-02', 'valor_terreno' => 8690000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => 'Pie + cuotas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Daniel Agurto Flores', 'comuna_residencia' => 'Valdivia', 'telefono' => '953968247', 'correo' => 'daniel.agurto.flores@gmail.com', 'etapa' => 'I', 'numero_parcela' => '16-17', 'como_se_entero' => 'RRSS', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Moisés Arroyo', 'medio_contacto_vendedor' => 'wasap/Mail', 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => 'transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Álvaro Paredes', 'comuna_residencia' => 'La Florida', 'telefono' => '956099638', 'correo' => 'alvaroparedesl@gmail.com', 'etapa' => 'I', 'numero_parcela' => '35 - 36', 'como_se_entero' => 'Dato de Terceros', 'medio_difusion' => null, 'contacto_vendedor_nombre' => 'Moises Arroyo', 'medio_contacto_vendedor' => 'Whatsapp / Email', 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Nombre: inversiones latam spa\nBanco: BCI\nCuenta Corriente: 0-000-46-18688-3\nRUT: 77.141.857-0\nMail: tupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => 'pagada', 'registro_pagos' => 'si', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'Miguel Alejandro Risco Velásquez', 'comuna_residencia' => 'Valdivia', 'telefono' => '986045465 / 977996055', 'correo' => 'miguelriscovelasquez@gmail.com / miguelrisco41@gmail.com', 'etapa' => 'II', 'numero_parcela' => '35 y 36', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => 'Daniela Osben', 'medio_contacto_vendedor' => 'Email', 'fecha_firma_contrato' => '2021-04-06', 'valor_terreno' => 13890000, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => "Las primeras fueron a RUT 77.141.857-0\nCuenta 46186883\nBanco Bci\nMail contacto@inversioneslatam.cl las últimas 3 a RUT 77.702.194-K Cuenta 89821894\nBanco Banco Santander\nMail tupagoaldia@inversioneslatam.cl", 'plazo_pago_entrega' => 'Pie de 1.000.000 el saldo en 31 coutas', 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
            ['nombres_apellidos' => 'María Araya Campos', 'comuna_residencia' => null, 'telefono' => '932597822', 'correo' => 'marayac30@gmail.com', 'etapa' => 'I', 'numero_parcela' => '40 - 41 - 43', 'como_se_entero' => null, 'medio_difusion' => null, 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => null, 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => null, 'estado_parcela' => null],
            ['nombres_apellidos' => 'Estefany Maldonado', 'comuna_residencia' => null, 'telefono' => '937101816', 'correo' => 'maldonado.estefany@gmail.com', 'etapa' => 'I y II', 'numero_parcela' => '55 - 3', 'como_se_entero' => 'Redes Sociales', 'medio_difusion' => 'Instagram', 'contacto_vendedor_nombre' => null, 'medio_contacto_vendedor' => null, 'fecha_firma_contrato' => null, 'valor_terreno' => null, 'forma_pago' => 'Transferencia', 'datos_cuenta_pago' => null, 'plazo_pago_entrega' => null, 'registro_pagos' => 'SI', 'estado_parcela' => 'Inscrita'],
        ];

        foreach ($vecinos as $data) {
            if (empty($data['nombres_apellidos'])) {
                continue;
            }

            Vecino::firstOrCreate(
                [
                    'nombres_apellidos' => $data['nombres_apellidos'],
                    'etapa'             => $data['etapa'],
                    'numero_parcela'    => $data['numero_parcela'],
                ],
                array_diff_key($data, array_flip(['nombres_apellidos', 'etapa', 'numero_parcela']))
            );
        }
    }
}
